## Numpy Introduction

In [1]:
# pip install numpy

In [2]:
# import the library
import numpy as np

## What is an array?
An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis, and machine learning.

In Python, the NumPy library provides support for arrays and enables efficient numerical operations on them. NumPy arrays are more efficient than Python lists for numerical operations because they are implemented in C and allow for vectorized operations.

In [3]:
# One dimensional array
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [4]:
# Two dimensional array
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [5]:
# Another Way
a2 = a[: , np.newaxis]
print(a2)
a2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [6]:
# Two dimensional array
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [7]:
# Three dimensional array
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating Arrays With Numpy

In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])

In [9]:
type(a) # type of array

numpy.ndarray

In [10]:
a.dtype # data type of array elements

dtype('int64')

In [11]:
type(b) # type of array

numpy.ndarray

In [12]:
b.dtype

dtype('int64')

In [13]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [14]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

## Initialize Arrays

In [15]:
zeros = np.zeros((2, 5)) # (rows, columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
ones = np.ones((2, 5)) # (rows, columns)
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
full = np.full((2, 5), 7)
full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
full.dtype

dtype('int64')

In [37]:
# Creating an Identity Matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
identity.dtype

dtype('float64')

## Array Attributes

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a.shape # shape of array

(7,)

In [39]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [40]:
b.shape

(2, 7)

In [24]:
len(b)  # gives us the length of array

2

In [25]:
b.size # gives us the number of elements in the array

14

In [26]:
b.ndim  # gives us the dimension of an array

2

## Basic Operations

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [29]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [30]:
h = a + b # addition
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [31]:
# Another way to add two arrays by np.add()
h = np.add(a, b)
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [32]:
i = a * b # multiplication
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [33]:
j = a / b # division
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [34]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
k = a ** 2 # square of each element
k

array([ 1,  4,  9, 16, 25, 36, 49])