## Numpy (Part-2)

In [76]:
import numpy as np

In [77]:
# Creating an empty with 2 elements
empty = np.empty((2,3))
print(empty)
print('-------')
print(empty[0])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.33644469e-307 2.67018777e-306 2.42092166e-322]]
-------
[6.23042070e-307 4.67296746e-307 1.69121096e-306]


In [78]:
# Creating an empty with 2 elements
empty = np.empty((2,4))
print(empty)
print('-------')
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------
[0. 0. 0. 0.]


In [79]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [80]:
# array of even numbers from 0 to 23
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [81]:
# array of odd numbers from 0 to 23
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [82]:
# specific difference between numbers
diff = np.arange(0, 23, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [83]:
# specific difference between numbers
diff = np.arange(0, 23, 0.515) # 0.515 is the specific difference between numbers
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

In [84]:
lin = np.linspace(0, 10, num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [85]:
lin = np.linspace(0, 10, num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [86]:
lin = np.linspace(0, 10, num=1700000)
lin

array([0.00000000e+00, 5.88235640e-06, 1.17647128e-05, ...,
       9.99998824e+00, 9.99999412e+00, 1.00000000e+01])

In [87]:
lin = np.linspace(0, 10, num=15)
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [88]:
lin.dtype

dtype('float64')

In [89]:
x = np.ones(2)
x

array([1., 1.])

In [90]:
# define the dtype of array
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

In [91]:
#convert data type
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [92]:
# define the dtype of array
x = np.arange(2, dtype=np.float64)
x

array([0., 1.])

In [93]:
#convert data type
x = np.arange(2, dtype=np.int64)
x

array([0, 1])

In [94]:
# define the dtype of array
x = np.arange(22.6, dtype=np.float64)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

In [95]:
# define the dtype of array
x = np.arange(0, 22.6, 1.5, dtype=np.float64)
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5])

In [96]:
# define the dtype of array
x = np.arange(0, 22.6, 1.5, dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [97]:
# sorting an array
x1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
x1

array([2, 1, 5, 3, 7, 4, 6, 8])

In [98]:
x2 = np.sort(x1)
x2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
a = np.array([1, 2, 3, 6, 5])
b = np.array([6, 7, 8, 9, 10])

In [100]:
# concatenate these arrays
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  6,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Arrays

In [101]:
x = np.array([[1, 2], [3, 4]]) # 2x2 array
y = np.array([[5, 6]]) # 1x2 array

In [102]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0) # axis=0 can be apply only on when lengths are not same(like in x and y).
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
w= np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [104]:
z1 = np.concatenate((w,x), axis=0)
z1

array([[5, 1],
       [7, 1],
       [1, 2],
       [3, 4]])

In [105]:
z1 = np.concatenate((w,x), axis=1) # axis=1 apply because lengths of w and x are equal
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [106]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [107]:
array_example.ndim

3

In [108]:
len(array_example)

3

In [109]:
array_example.size

24

In [110]:
array_example.dtype

dtype('int64')

In [111]:
array_example.shape

(3, 2, 4)

In [112]:
# create 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [113]:
a1.shape

(3, 1, 4)

In [114]:
# reshape the a1 
a2 = a1.reshape(6,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [115]:
a2.shape

(6, 2)

In [116]:
a3 = a2.reshape(3,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [117]:
a3.shape

(3, 2, 2)

In [118]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [119]:
# convert that into 2D array
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [120]:
b.shape

(1, 8)

In [121]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [122]:
c.shape

(8, 1)

# indexing and slicing

In [123]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
a[2]

np.int64(3)

In [125]:
a[2:5]

array([3, 4, 5])

In [126]:
a[-4:]

array([5, 6, 7, 8])

In [127]:
a[-4: -2]

array([5, 6])

In [128]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [129]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
b[0]

array([1, 2, 3, 4])

In [131]:
b[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [132]:
b[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [133]:
b[0:, 1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [134]:
b[0:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [135]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
b[b < 2]

array([1])

In [137]:
b[b < 5]

array([1, 2, 3, 4])

In [138]:
b[b > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [139]:
b[b > 10]

array([11, 12])

In [140]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [142]:
# filter odd numbers
b[b % 2 == 1] # % remainder function

array([ 1,  3,  5,  7,  9, 11])

In [143]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [144]:
# use two conditions
b[(b > 0) & (b < 12)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [149]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])