## Numpy Indexing and Slicing

In [92]:
import numpy as np

In [93]:
# create an array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [94]:
a[1:5]

array([2, 3, 4, 5])

In [95]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [96]:
b.shape

(6,)

In [97]:
b[2]

np.int64(4)

In [98]:
c = b.reshape(3, 2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [99]:
c[0]

array([0, 2])

In [100]:
c[1:, 1:]

array([[ 6],
       [10]])

In [101]:
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [102]:
c[(c < 5) | (c > 7)]

array([ 0,  2,  4,  8, 10])

## Enlist boolean operators conditional operators?
______________
# Making an array from a data or another array

In [103]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [104]:
len(a)

45

In [105]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [106]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [107]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [108]:
b

array([ 8,  9, 10, 11, 12, 13, 14])

In [109]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [110]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

_____
# Matrix or Matrices

In [112]:
# create a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
a[1]

array([4, 5, 6])

In [114]:
# create a matrix
b = np.arange(0, 100, 2).reshape(5,10)
b 

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [115]:
b[:, :]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [116]:
# slicing a matrix of 3x2
c = b[0:3, 3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [117]:
# slicing a matrix of 3x2
c = b[0:5,3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48],
       [66, 68],
       [86, 88]])

In [118]:
b.max()

np.int64(98)

In [119]:
b.min()

np.int64(0)

In [120]:
b.sum()

np.int64(2450)

In [121]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [122]:
b.max(axis=0) # only for column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [123]:
b.max(axis=1) # only for row

array([18, 38, 58, 78, 98])

In [124]:
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [125]:
b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [126]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [127]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [128]:
m - np.array([20, 22])

array([[-20, -20],
       [-16, -16],
       [-12, -12],
       [ -8,  -8],
       [ -4,  -4]])

In [129]:
m * np.array([20, 22])

array([[  0,  44],
       [ 80, 132],
       [160, 220],
       [240, 308],
       [320, 396]])

In [130]:
m / np.array([20, 22])

array([[0.        , 0.09090909],
       [0.2       , 0.27272727],
       [0.4       , 0.45454545],
       [0.6       , 0.63636364],
       [0.8       , 0.81818182]])

In [131]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [132]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [133]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])